"""empty message

Revision ID: 285230292927
Revises: 3607ff4b32d9
Create Date: 2017-08-16 15:57:57.320753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285230292927'
down_revision = '3607ff4b32d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betfreds', sa.Column('clito', sa.Integer(), nullable=True))
    op.add_column('betfreds', sa.Column('commito', sa.Float(), nullable=True))
    op.add_column('betfreds', sa.Column('impreto', sa.Integer(), nullable=True))
    op.add_column('betfreds', sa.Column('ndto', sa.Integer(), nullable=True))
    op.add_column('betfreds', sa.Column('regto', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('betfreds', 'regto')
    op.drop_column('betfreds', 'ndto')
    op.drop_column('betfreds', 'impreto')
    op.drop_column('betfreds', 'commito')
    op.drop_column('betfreds', 'clito')
    # ### end Alembic commands ###
