"""empty message

Revision ID: 292eba80bf88
Revises: f05450b59b10
Create Date: 2017-09-08 11:40:19.353000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '292eba80bf88'
down_revision = 'f05450b59b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ladbrokes', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('ladbrokes', sa.Column('monthly_click', sa.Integer(), nullable=True))
    op.add_column('ladbrokes', sa.Column('monthly_commission', sa.Float(), nullable=True))
    op.add_column('ladbrokes', sa.Column('monthly_signup', sa.Integer(), nullable=True))
    op.add_column('ladbrokes', sa.Column('paid_signup', sa.Integer(), nullable=True))
    op.add_column('ladbrokes', sa.Column('signup', sa.Integer(), nullable=True))
    op.add_column('ladbrokes', sa.Column('yearly_click', sa.Integer(), nullable=True))
    op.add_column('ladbrokes', sa.Column('yearly_commission', sa.Float(), nullable=True))
    op.add_column('ladbrokes', sa.Column('yearly_signup', sa.Integer(), nullable=True))
    op.drop_constraint(u'ladbrokes_dateto_key', 'ladbrokes', type_='unique')
    op.create_unique_constraint(None, 'ladbrokes', ['created_at'])
    op.drop_column('ladbrokes', 'merchant')
    op.drop_column('ladbrokes', 'impression')
    op.drop_column('ladbrokes', 'impreto')
    op.drop_column('ladbrokes', 'ndytd')
    op.drop_column('ladbrokes', 'dateto')
    op.drop_column('ladbrokes', 'commiytd')
    op.drop_column('ladbrokes', 'impreytd')
    op.drop_column('ladbrokes', 'ndto')
    op.drop_column('ladbrokes', 'commito')
    op.drop_column('ladbrokes', 'new_deposit')
    op.drop_column('ladbrokes', 'registration')
    op.drop_column('ladbrokes', 'clito')
    op.drop_column('ladbrokes', 'regto')
    op.drop_column('ladbrokes', 'cliytd')
    op.drop_column('ladbrokes', 'regytd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ladbrokes', sa.Column('regytd', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('cliytd', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('regto', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('clito', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('registration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('new_deposit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('commito', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('ndto', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('impreytd', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('commiytd', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('dateto', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('ndytd', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('impreto', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('impression', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ladbrokes', sa.Column('merchant', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ladbrokes', type_='unique')
    op.create_unique_constraint(u'ladbrokes_dateto_key', 'ladbrokes', ['dateto'])
    op.drop_column('ladbrokes', 'yearly_signup')
    op.drop_column('ladbrokes', 'yearly_commission')
    op.drop_column('ladbrokes', 'yearly_click')
    op.drop_column('ladbrokes', 'signup')
    op.drop_column('ladbrokes', 'paid_signup')
    op.drop_column('ladbrokes', 'monthly_signup')
    op.drop_column('ladbrokes', 'monthly_commission')
    op.drop_column('ladbrokes', 'monthly_click')
    op.drop_column('ladbrokes', 'created_at')
    # ### end Alembic commands ###
