"""empty message

Revision ID: 2c5e1c4ab272
Revises: d67b9ea19bdc
Create Date: 2017-09-07 15:21:35.226000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5e1c4ab272'
down_revision = 'd67b9ea19bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corals', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'corals', ['dateto'])
    op.add_column('eight88s', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'eight88s', ['dateto'])
    op.add_column('ladbrokes', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'ladbrokes', ['dateto'])
    op.add_column('netbets', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'netbets', ['dateto'])
    op.add_column('paddyies', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'paddyies', ['dateto'])
    op.add_column('realdeals', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'realdeals', ['dateto'])
    op.add_column('skybets', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'skybets', ['dateto'])
    op.add_column('stans', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'stans', ['dateto'])
    op.add_column('titanbets', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'titanbets', ['dateto'])
    op.add_column('williams', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'williams', ['dateto'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'williams', type_='unique')
    op.drop_column('williams', 'dateto')
    op.drop_constraint(None, 'titanbets', type_='unique')
    op.drop_column('titanbets', 'dateto')
    op.drop_constraint(None, 'stans', type_='unique')
    op.drop_column('stans', 'dateto')
    op.drop_constraint(None, 'skybets', type_='unique')
    op.drop_column('skybets', 'dateto')
    op.drop_constraint(None, 'realdeals', type_='unique')
    op.drop_column('realdeals', 'dateto')
    op.drop_constraint(None, 'paddyies', type_='unique')
    op.drop_column('paddyies', 'dateto')
    op.drop_constraint(None, 'netbets', type_='unique')
    op.drop_column('netbets', 'dateto')
    op.drop_constraint(None, 'ladbrokes', type_='unique')
    op.drop_column('ladbrokes', 'dateto')
    op.drop_constraint(None, 'eight88s', type_='unique')
    op.drop_column('eight88s', 'dateto')
    op.drop_constraint(None, 'corals', type_='unique')
    op.drop_column('corals', 'dateto')
    # ### end Alembic commands ###
