"""empty message

Revision ID: 7139a12aed44
Revises: 292eba80bf88
Create Date: 2017-09-08 15:56:02.034000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7139a12aed44'
down_revision = '292eba80bf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netbets', sa.Column('click', sa.Integer(), nullable=True))
    op.add_column('netbets', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('netbets', sa.Column('monthly_click', sa.Integer(), nullable=True))
    op.add_column('netbets', sa.Column('monthly_commission', sa.Float(), nullable=True))
    op.add_column('netbets', sa.Column('monthly_signup', sa.Integer(), nullable=True))
    op.add_column('netbets', sa.Column('paid_signup', sa.Integer(), nullable=True))
    op.add_column('netbets', sa.Column('signup', sa.Integer(), nullable=True))
    op.add_column('netbets', sa.Column('yearly_click', sa.Integer(), nullable=True))
    op.add_column('netbets', sa.Column('yearly_commission', sa.Float(), nullable=True))
    op.add_column('netbets', sa.Column('yearly_signup', sa.Integer(), nullable=True))
    op.drop_constraint(u'netbets_dateto_key', 'netbets', type_='unique')
    op.create_unique_constraint(None, 'netbets', ['created_at'])
    op.drop_column('netbets', 'withdraw_amount')
    op.drop_column('netbets', 'withdraw_count')
    op.drop_column('netbets', 'impressions_count')
    op.drop_column('netbets', 'bonus_bets_amount')
    op.drop_column('netbets', 'first_deposits_count')
    op.drop_column('netbets', 'rakes_amount')
    op.drop_column('netbets', 'bonus_count')
    op.drop_column('netbets', 'net_revenue')
    op.drop_column('netbets', 'downloads_count')
    op.drop_column('netbets', 'bonus_amount')
    op.drop_column('netbets', 'first_deposits_amount')
    op.drop_column('netbets', 'bonus_wins_amount')
    op.drop_column('netbets', 'deposits_count')
    op.drop_column('netbets', 'invalid_cpa')
    op.drop_column('netbets', 'gross_revenue')
    op.drop_column('netbets', 'dateto')
    op.drop_column('netbets', 'valid_cpa')
    op.drop_column('netbets', 'affiliate_website_id')
    op.drop_column('netbets', 'pending_cpa')
    op.drop_column('netbets', 'cash_wins_amount')
    op.drop_column('netbets', 'fees_amount')
    op.drop_column('netbets', 'clicks_count')
    op.drop_column('netbets', 'url')
    op.drop_column('netbets', 'deposits_amount')
    op.drop_column('netbets', 'registrations')
    op.drop_column('netbets', 'cash_bets_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netbets', sa.Column('cash_bets_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('registrations', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('deposits_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('clicks_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('fees_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('cash_wins_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('pending_cpa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('affiliate_website_id', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('valid_cpa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('dateto', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('gross_revenue', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('invalid_cpa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('deposits_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('bonus_wins_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('first_deposits_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('bonus_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('downloads_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('net_revenue', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('bonus_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('rakes_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('first_deposits_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('bonus_bets_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('impressions_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('withdraw_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('netbets', sa.Column('withdraw_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netbets', type_='unique')
    op.create_unique_constraint(u'netbets_dateto_key', 'netbets', ['dateto'])
    op.drop_column('netbets', 'yearly_signup')
    op.drop_column('netbets', 'yearly_commission')
    op.drop_column('netbets', 'yearly_click')
    op.drop_column('netbets', 'signup')
    op.drop_column('netbets', 'paid_signup')
    op.drop_column('netbets', 'monthly_signup')
    op.drop_column('netbets', 'monthly_commission')
    op.drop_column('netbets', 'monthly_click')
    op.drop_column('netbets', 'created_at')
    op.drop_column('netbets', 'click')
    # ### end Alembic commands ###
