"""empty message

Revision ID: aaf48c80d94a
Revises: 
Create Date: 2017-09-06 12:10:17.523000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf48c80d94a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet10s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=80), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('new_deposit', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('impreytd', sa.Integer(), nullable=True),
    sa.Column('cliytd', sa.Integer(), nullable=True),
    sa.Column('regytd', sa.Integer(), nullable=True),
    sa.Column('ndytd', sa.Integer(), nullable=True),
    sa.Column('commiytd', sa.Float(), nullable=True),
    sa.Column('impreto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regto', sa.Integer(), nullable=True),
    sa.Column('ndto', sa.Integer(), nullable=True),
    sa.Column('commito', sa.Float(), nullable=True),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('bet365others',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('nsignup', sa.Integer(), nullable=True),
    sa.Column('ndepo', sa.Integer(), nullable=True),
    sa.Column('valdepo', sa.Float(), nullable=True),
    sa.Column('numdepo', sa.Integer(), nullable=True),
    sa.Column('spotsturn', sa.Float(), nullable=True),
    sa.Column('numsptbet', sa.Integer(), nullable=True),
    sa.Column('acsptusr', sa.Integer(), nullable=True),
    sa.Column('sptnetrev', sa.Float(), nullable=True),
    sa.Column('casinonetrev', sa.Float(), nullable=True),
    sa.Column('pokernetrev', sa.Float(), nullable=True),
    sa.Column('bingonetrev', sa.Float(), nullable=True),
    sa.Column('netrev', sa.Float(), nullable=True),
    sa.Column('afspt', sa.Float(), nullable=True),
    sa.Column('afcasino', sa.Float(), nullable=True),
    sa.Column('afpoker', sa.Float(), nullable=True),
    sa.Column('afbingo', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('bet365s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('nsignup', sa.Integer(), nullable=True),
    sa.Column('ndepo', sa.Integer(), nullable=True),
    sa.Column('valdepo', sa.Float(), nullable=True),
    sa.Column('numdepo', sa.Integer(), nullable=True),
    sa.Column('spotsturn', sa.Float(), nullable=True),
    sa.Column('numsptbet', sa.Integer(), nullable=True),
    sa.Column('acsptusr', sa.Integer(), nullable=True),
    sa.Column('sptnetrev', sa.Float(), nullable=True),
    sa.Column('casinonetrev', sa.Float(), nullable=True),
    sa.Column('pokernetrev', sa.Float(), nullable=True),
    sa.Column('bingonetrev', sa.Float(), nullable=True),
    sa.Column('netrev', sa.Float(), nullable=True),
    sa.Column('afspt', sa.Float(), nullable=True),
    sa.Column('afcasino', sa.Float(), nullable=True),
    sa.Column('afpoker', sa.Float(), nullable=True),
    sa.Column('afbingo', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('betfreds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=80), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('new_deposit', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('impreytd', sa.Integer(), nullable=True),
    sa.Column('cliytd', sa.Integer(), nullable=True),
    sa.Column('regytd', sa.Integer(), nullable=True),
    sa.Column('ndytd', sa.Integer(), nullable=True),
    sa.Column('commiytd', sa.Float(), nullable=True),
    sa.Column('impreto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regto', sa.Integer(), nullable=True),
    sa.Column('ndto', sa.Integer(), nullable=True),
    sa.Column('commito', sa.Float(), nullable=True),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('corals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=80), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('new_deposit', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('impreytd', sa.Integer(), nullable=True),
    sa.Column('cliytd', sa.Integer(), nullable=True),
    sa.Column('regytd', sa.Integer(), nullable=True),
    sa.Column('ndytd', sa.Integer(), nullable=True),
    sa.Column('commiytd', sa.Float(), nullable=True),
    sa.Column('impreto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regto', sa.Integer(), nullable=True),
    sa.Column('ndto', sa.Integer(), nullable=True),
    sa.Column('commito', sa.Float(), nullable=True),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('eight88s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('lead', sa.Integer(), nullable=True),
    sa.Column('money_player', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('prebalance', sa.Float(), nullable=True),
    sa.Column('imprwk', sa.Integer(), nullable=True),
    sa.Column('cliwk', sa.Integer(), nullable=True),
    sa.Column('regwk', sa.Integer(), nullable=True),
    sa.Column('leadwk', sa.Integer(), nullable=True),
    sa.Column('mpwk', sa.Integer(), nullable=True),
    sa.Column('imprpre', sa.Integer(), nullable=True),
    sa.Column('clipre', sa.Integer(), nullable=True),
    sa.Column('regpre', sa.Integer(), nullable=True),
    sa.Column('leadpre', sa.Integer(), nullable=True),
    sa.Column('mppre', sa.Integer(), nullable=True),
    sa.Column('imprto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regto', sa.Integer(), nullable=True),
    sa.Column('leadto', sa.Integer(), nullable=True),
    sa.Column('mpto', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ladbrokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netbets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paddyies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realdeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=80), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('new_deposit', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('impreytd', sa.Integer(), nullable=True),
    sa.Column('cliytd', sa.Integer(), nullable=True),
    sa.Column('regiytd', sa.Integer(), nullable=True),
    sa.Column('ndytd', sa.Integer(), nullable=True),
    sa.Column('commiytd', sa.Float(), nullable=True),
    sa.Column('impreto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regto', sa.Integer(), nullable=True),
    sa.Column('ndto', sa.Integer(), nullable=True),
    sa.Column('commito', sa.Float(), nullable=True),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('skybets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=80), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('new_deposit', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('impreytd', sa.Integer(), nullable=True),
    sa.Column('cliytd', sa.Integer(), nullable=True),
    sa.Column('regiytd', sa.Integer(), nullable=True),
    sa.Column('ndytd', sa.Integer(), nullable=True),
    sa.Column('commiytd', sa.Float(), nullable=True),
    sa.Column('impreto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regito', sa.Integer(), nullable=True),
    sa.Column('ndto', sa.Integer(), nullable=True),
    sa.Column('commito', sa.Float(), nullable=True),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('stans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=80), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('new_deposit', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('imprytd', sa.Integer(), nullable=True),
    sa.Column('cliytd', sa.Integer(), nullable=True),
    sa.Column('regytd', sa.Integer(), nullable=True),
    sa.Column('ndytd', sa.Integer(), nullable=True),
    sa.Column('commiytd', sa.Float(), nullable=True),
    sa.Column('imprto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regto', sa.Integer(), nullable=True),
    sa.Column('ndto', sa.Integer(), nullable=True),
    sa.Column('commito', sa.Float(), nullable=True),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('titanbets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('victors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=80), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('new_deposit', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('impreytd', sa.Integer(), nullable=True),
    sa.Column('cliytd', sa.Integer(), nullable=True),
    sa.Column('regytd', sa.Integer(), nullable=True),
    sa.Column('ndytd', sa.Integer(), nullable=True),
    sa.Column('commiytd', sa.Float(), nullable=True),
    sa.Column('impreto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regto', sa.Integer(), nullable=True),
    sa.Column('ndto', sa.Integer(), nullable=True),
    sa.Column('commito', sa.Float(), nullable=True),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    op.create_table('williams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('williams')
    op.drop_table('victors')
    op.drop_table('users')
    op.drop_table('titanbets')
    op.drop_table('stans')
    op.drop_table('skybets')
    op.drop_table('realdeals')
    op.drop_table('paddyies')
    op.drop_table('netbets')
    op.drop_table('ladbrokes')
    op.drop_table('eight88s')
    op.drop_table('corals')
    op.drop_table('betfreds')
    op.drop_table('bet365s')
    op.drop_table('bet365others')
    op.drop_table('bet10s')
    # ### end Alembic commands ###
