"""empty message

Revision ID: b57f08768fcd
Revises: 
Create Date: 2017-08-24 18:36:50.954699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57f08768fcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet10s', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'bet10s', ['dateto'])
    op.add_column('betfreds', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'betfreds', ['dateto'])
    op.add_column('corals', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'corals', ['dateto'])
    op.add_column('realdeals', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'realdeals', ['dateto'])
    op.add_column('skybets', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'skybets', ['dateto'])
    op.add_column('stans', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'stans', ['dateto'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stans', type_='unique')
    op.drop_column('stans', 'dateto')
    op.drop_constraint(None, 'skybets', type_='unique')
    op.drop_column('skybets', 'dateto')
    op.drop_constraint(None, 'realdeals', type_='unique')
    op.drop_column('realdeals', 'dateto')
    op.drop_constraint(None, 'corals', type_='unique')
    op.drop_column('corals', 'dateto')
    op.drop_constraint(None, 'betfreds', type_='unique')
    op.drop_column('betfreds', 'dateto')
    op.drop_constraint(None, 'bet10s', type_='unique')
    op.drop_column('bet10s', 'dateto')
    # ### end Alembic commands ###
