"""empty message

Revision ID: c4ec2186dc15
Revises: d921068aa881
Create Date: 2017-09-08 22:35:39.903000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ec2186dc15'
down_revision = 'd921068aa881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('victors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateto', sa.Date(), nullable=True),
    sa.Column('merchant', sa.String(length=80), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Integer(), nullable=True),
    sa.Column('new_deposit', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('impreytd', sa.Integer(), nullable=True),
    sa.Column('cliytd', sa.Integer(), nullable=True),
    sa.Column('regytd', sa.Integer(), nullable=True),
    sa.Column('ndytd', sa.Integer(), nullable=True),
    sa.Column('commiytd', sa.Float(), nullable=True),
    sa.Column('impreto', sa.Integer(), nullable=True),
    sa.Column('clito', sa.Integer(), nullable=True),
    sa.Column('regto', sa.Integer(), nullable=True),
    sa.Column('ndto', sa.Integer(), nullable=True),
    sa.Column('commito', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('victors')
    # ### end Alembic commands ###
