"""empty message

Revision ID: c8c1d6b1c975
Revises: 7139a12aed44
Create Date: 2017-09-08 18:26:18.538000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c1d6b1c975'
down_revision = '7139a12aed44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stans', sa.Column('impreytd', sa.Integer(), nullable=True))
    op.drop_column('stans', 'imprytd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stans', sa.Column('imprytd', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stans', 'impreytd')
    # ### end Alembic commands ###
