"""empty message

Revision ID: d67b9ea19bdc
Revises: 82bdf13304ff
Create Date: 2017-09-07 15:16:12.354000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67b9ea19bdc'
down_revision = '82bdf13304ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet10s', sa.Column('dateto', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'bet10s', ['dateto'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet10s', type_='unique')
    op.drop_column('bet10s', 'dateto')
    # ### end Alembic commands ###
