"""empty message

Revision ID: d921068aa881
Revises: c8c1d6b1c975
Create Date: 2017-09-08 20:27:24.973000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd921068aa881'
down_revision = 'c8c1d6b1c975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skybets', sa.Column('imprto', sa.Integer(), nullable=True))
    op.add_column('skybets', sa.Column('regytd', sa.Integer(), nullable=True))
    op.drop_column('skybets', 'impreto')
    op.drop_column('skybets', 'regiytd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skybets', sa.Column('regiytd', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('skybets', sa.Column('impreto', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('skybets', 'regytd')
    op.drop_column('skybets', 'imprto')
    # ### end Alembic commands ###
