"""empty message

Revision ID: d96a6485b675
Revises: 
Create Date: 2017-08-14 17:35:57.826108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96a6485b675'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eight88s', sa.Column('prebalance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eight88s', 'prebalance')
    # ### end Alembic commands ###
