"""empty message

Revision ID: f60442f5e489
Revises: c4ec2186dc15
Create Date: 2017-09-08 23:24:30.450000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f60442f5e489'
down_revision = 'c4ec2186dc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('williams', sa.Column('click', sa.Integer(), nullable=True))
    op.add_column('williams', sa.Column('commission', sa.Float(), nullable=True))
    op.add_column('williams', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('williams', sa.Column('monthly_click', sa.Integer(), nullable=True))
    op.add_column('williams', sa.Column('monthly_commission', sa.Float(), nullable=True))
    op.add_column('williams', sa.Column('monthly_signup', sa.Integer(), nullable=True))
    op.add_column('williams', sa.Column('paid_signup', sa.Integer(), nullable=True))
    op.add_column('williams', sa.Column('signup', sa.Integer(), nullable=True))
    op.add_column('williams', sa.Column('yearly_click', sa.Integer(), nullable=True))
    op.add_column('williams', sa.Column('yearly_commission', sa.Float(), nullable=True))
    op.add_column('williams', sa.Column('yearly_signup', sa.Integer(), nullable=True))
    op.drop_constraint(u'williams_dateto_key', 'williams', type_='unique')
    op.create_unique_constraint(None, 'williams', ['created_at'])
    op.drop_column('williams', 'unique_views')
    op.drop_column('williams', 'net_revenue')
    op.drop_column('williams', 'active_customers')
    op.drop_column('williams', 'dateto')
    op.drop_column('williams', 'views')
    op.drop_column('williams', 'depositing_customers')
    op.drop_column('williams', 'chargebacks')
    op.drop_column('williams', 'signups')
    op.drop_column('williams', 'balance')
    op.drop_column('williams', 'clicks')
    op.drop_column('williams', 'unique_clicks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('williams', sa.Column('unique_clicks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('signups', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('chargebacks', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('depositing_customers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('dateto', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('active_customers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('net_revenue', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('williams', sa.Column('unique_views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'williams', type_='unique')
    op.create_unique_constraint(u'williams_dateto_key', 'williams', ['dateto'])
    op.drop_column('williams', 'yearly_signup')
    op.drop_column('williams', 'yearly_commission')
    op.drop_column('williams', 'yearly_click')
    op.drop_column('williams', 'signup')
    op.drop_column('williams', 'paid_signup')
    op.drop_column('williams', 'monthly_signup')
    op.drop_column('williams', 'monthly_commission')
    op.drop_column('williams', 'monthly_click')
    op.drop_column('williams', 'created_at')
    op.drop_column('williams', 'commission')
    op.drop_column('williams', 'click')
    # ### end Alembic commands ###
